
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
  namespace: default
type: Opaque
data:
  influxdb_username: {{ .Values.influxdb_username | b64enc | quote}}
  influxdb_password: {{ .Values.influxdb_password | b64enc | quote}}
  influxdb_token: {{ .Values.influxdb_token | b64enc | quote}}